import type { Scorecard } from "../../prompt-eval-gate/index.js";

export type { Scorecard } from "../../prompt-eval-gate/index.js";

export interface ModelUpgradeSpec {
  currentModel: string;
  candidateModel: string;
  /** file the new model id is written to on approval */
  configPath: string;
}

/** Runs the golden eval set on a given model and returns its scorecard. */
export type ModelEvaluator = (modelId: string) => Promise<Scorecard>;

export interface ModelUpgradeServices {
  evaluate: ModelEvaluator;
}

export function renderUpgradeReport(
  spec: ModelUpgradeSpec,
  baseline: Scorecard,
  candidate: Scorecard,
  regressed: string[],
  dateIso: string,
): string {
  const delta = Math.round((candidate.score - baseline.score) * 100);
  const sign = delta >= 0 ? "+" : "";
  return [
    `## Model upgrade: ${spec.currentModel} → ${spec.candidateModel} — ${dateIso}`,
    "",
    `- Score: ${Math.round(baseline.score * 100)}% → ${Math.round(candidate.score * 100)}% (${sign}${delta} pts)`,
    `- Regressions: ${regressed.length}`,
    ...(regressed.length > 0 ? regressed.map((id) => `  - \`${id}\` passes now, fails on the candidate`) : []),
    "",
    "_Generated by loopy model-upgrade-migration. The switch is human-gated._",
  ].join("\n");
}
