import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  Trigger,
} from "../../src/core/index.js";
import { findGaps, type KbGap, type TicketSource } from "./hooks/gaps.js";

export interface KbGapConfig {
  /** directory the loop is allowed to write KB articles into (default "docs/kb") */
  kbDir: string;
  /** minimum recurring tickets on a topic before it counts as a gap (default 3) */
  minTickets: number;
}

export interface DocChange {
  path: string;
  contents: string;
}

/**
 * The AI step (driven by `playbook.md`): given the detected gaps, return the
 * contents of any KB articles to write. This is the loop's only
 * provider-specific boundary; detection is fully deterministic.
 */
export type ArticleWriter = (gaps: KbGap[]) => Promise<DocChange[]>;

export interface KbGapServices {
  tickets: TicketSource;
  coveredTopics: () => Promise<string[]>;
  articleWriter: ArticleWriter;
}

/** Build the kb-gap loop from explicit config + the injected services. */
export function createKbGapLoop(
  config: KbGapConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: KbGapServices,
): Loop {
  async function computeGaps(): Promise<KbGap[]> {
    const tickets = await services.tickets.listResolved();
    const covered = await services.coveredTopics();
    return findGaps(tickets, covered, config.minTickets);
  }

  return {
    id: "kb-gap",
    trigger,
    guardrails,

    async detect(): Promise<DetectResult> {
      const gaps = await computeGaps();
      if (gaps.length === 0) {
        return { workNeeded: false, reason: "no recurring documentation gaps" };
      }
      return {
        workNeeded: true,
        reason: `${gaps.length} doc gap(s)`,
        affected: gaps.map((g) => g.topic),
      };
    },

    async act(): Promise<ActResult> {
      const gaps = await computeGaps();
      const docChanges = await services.articleWriter(gaps);

      if (docChanges.length === 0) {
        return { changes: [], summary: "No KB articles drafted; the writer declined every gap." };
      }

      const changes: FileChange[] = docChanges.map((d) => ({
        path: d.path,
        op: "write",
        contents: d.contents,
      }));

      return { changes, summary: summarize(docChanges) };
    },
  };
}

/** Build the kb-gap loop from a parsed `loop.yaml` manifest. */
export function createKbGapLoopFromManifest(
  manifest: LoopManifest,
  services: KbGapServices,
): Loop {
  const c = manifest.config;
  const config: KbGapConfig = {
    kbDir: typeof c["kbDir"] === "string" ? c["kbDir"] : "docs/kb",
    minTickets: typeof c["minTickets"] === "number" ? c["minTickets"] : 3,
  };
  return createKbGapLoop(config, manifest.guardrails, manifest.trigger, services);
}

function summarize(docChanges: DocChange[]): string {
  const docLines = docChanges.map((d) => `- \`${d.path}\``);
  return [
    "## KB-gap self-heal",
    "",
    "Drafted knowledge-base articles for recurring support topics:",
    ...docLines,
    "",
    "_Generated by loopy kb-gap. Review before merging._",
  ].join("\n");
}

export type { Ticket, TicketSource, KbGap } from "./hooks/gaps.js";
export { findGaps, normalizeTopic } from "./hooks/gaps.js";
