import type {
  ActResult,
  DetectResult,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import {
  filterActionable,
  type Finding,
  type FindingsProvider,
  type Severity,
} from "./hooks/findings.js";
import { mergeChanges, type Fixer } from "./hooks/fix.js";

export interface SecurityRemediationConfig {
  /** minimum severity to act on (default "high") */
  severityThreshold: Severity;
}

export interface SecurityRemediationServices {
  findings: FindingsProvider;
  fixer: Fixer;
}

/**
 * Security remediation loop. Acts on scanner findings at or above a severity
 * threshold (false positives excluded), proposing fixes via a human-gated PR.
 * Never auto-merges.
 */
export function createSecurityRemediationLoop(
  config: SecurityRemediationConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: SecurityRemediationServices,
): Loop {
  async function actionable(): Promise<Finding[]> {
    return filterActionable(await services.findings.list(), config.severityThreshold);
  }

  return {
    id: "security-remediation",
    trigger,
    guardrails,

    async detect(ctx: RunContext): Promise<DetectResult> {
      void ctx;
      const findings = await actionable();
      if (findings.length === 0) {
        return { workNeeded: false, reason: "no actionable findings above threshold" };
      }
      return {
        workNeeded: true,
        reason: `${findings.length} actionable finding(s)`,
        affected: findings.map((f) => f.id),
      };
    },

    async act(ctx: RunContext): Promise<ActResult> {
      void ctx;
      const findings = await actionable();
      const fixSets = await Promise.all(findings.map((f) => services.fixer(f)));
      const fixed = findings.filter((_, i) => (fixSets[i] ?? []).length > 0);
      const changes = mergeChanges(fixSets);

      if (changes.length === 0) {
        return { changes: [], summary: "no automatic fix available for the findings" };
      }

      return { changes, summary: summarize(findings, fixed) };
    },
  };
}

export function createSecurityRemediationLoopFromManifest(
  manifest: LoopManifest,
  services: SecurityRemediationServices,
): Loop {
  const threshold = manifest.config["severityThreshold"];
  const config: SecurityRemediationConfig = {
    severityThreshold: isSeverity(threshold) ? threshold : "high",
  };
  return createSecurityRemediationLoop(config, manifest.guardrails, manifest.trigger, services);
}

function isSeverity(value: unknown): value is Severity {
  return value === "low" || value === "medium" || value === "high" || value === "critical";
}

function summarize(actionable: Finding[], fixed: Finding[]): string {
  const lines = ["## Security remediation", "", "Fixes for:"];
  for (const f of fixed) {
    const pkg = f.package ? ` (\`${f.package}\`)` : "";
    lines.push(`- [${f.severity}] ${f.title}${pkg}`);
  }
  const unfixed = actionable.filter((f) => !fixed.includes(f));
  if (unfixed.length > 0) {
    lines.push("", "No automatic fix (review manually):");
    for (const f of unfixed) lines.push(`- [${f.severity}] ${f.title}`);
  }
  lines.push("", "_Generated by loopy security-remediation. Human review required — never auto-merge._");
  return lines.join("\n");
}

export type { Finding, FindingsProvider, Severity } from "./hooks/findings.js";
export { meetsThreshold, filterActionable } from "./hooks/findings.js";
export type { Fixer } from "./hooks/fix.js";
