import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import { classify, violations, type Classified, type SbomSource } from "./hooks/licenses.js";

/** Default license allowlist: permissive OSS licenses that are safe to use without review. */
const DEFAULT_ALLOWLIST = [
  "MIT",
  "ISC",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "CC0-1.0",
  "Unlicense",
];

export interface LicenseConfig {
  /** path the license report is written to (default "reports/licenses.md") */
  reportPath: string;
  /** licenses that are accepted without review */
  allowlist: string[];
}

export interface LicenseServices {
  sbom: SbomSource;
  /** clock boundary, injectable for deterministic output (default `new Date`) */
  now?: () => Date;
}

/** Build the license-sbom-drift loop from explicit config + the injected services. */
export function createLicenseSbomLoop(
  config: LicenseConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: LicenseServices,
): Loop {
  async function classifyCurrent(): Promise<Classified[]> {
    return classify(await services.sbom.current(), config.allowlist);
  }

  return {
    id: "license-sbom-drift",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const classified = await classifyCurrent();
      const v = violations(classified);
      if (v.length === 0) {
        return { workNeeded: false, reason: "all dependency licenses are allowed" };
      }
      return {
        workNeeded: true,
        reason: `${v.length} license(s) need review`,
        affected: v.map((c) => c.entry.name),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      const classified = await classifyCurrent();
      const date = isoDate((services.now ?? (() => new Date()))());

      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderLicenseReport(classified, date),
      };

      return { changes: [change], summary: summarize(classified) };
    },
  };
}

/** Build the license-sbom-drift loop from a parsed `loop.yaml` manifest. */
export function createLicenseSbomLoopFromManifest(
  manifest: LoopManifest,
  services: LicenseServices,
): Loop {
  const c = manifest.config;
  const rawAllowlist = c["allowlist"];
  const allowlist =
    Array.isArray(rawAllowlist) && rawAllowlist.length > 0
      ? rawAllowlist.filter((x): x is string => typeof x === "string")
      : DEFAULT_ALLOWLIST;
  const config: LicenseConfig = {
    reportPath: typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/licenses.md",
    allowlist,
  };
  return createLicenseSbomLoop(config, manifest.guardrails, manifest.trigger, services);
}

/**
 * Render the license report as markdown: a full table of every dependency plus a
 * flagged "⚠ Review" section listing the violations (denied + unknown).
 */
export function renderLicenseReport(classified: Classified[], dateIso: string): string {
  const lines: string[] = [`# License report — ${dateIso}`, ""];

  if (classified.length === 0) {
    lines.push("No dependencies found in the SBOM.");
    lines.push("");
    return lines.join("\n");
  }

  lines.push("| Package | Version | License | Status |");
  lines.push("|---------|---------|---------|--------|");
  for (const c of classified) {
    const license = c.entry.license === "" ? "(none)" : c.entry.license;
    lines.push(`| ${c.entry.name} | ${c.entry.version} | ${license} | ${c.status} |`);
  }
  lines.push("");

  const v = violations(classified);
  lines.push("## ⚠ Review");
  lines.push("");
  if (v.length === 0) {
    lines.push("All dependency licenses are on the allowlist. Nothing to review.");
  } else {
    const n = v.length;
    lines.push(`${n} ${n === 1 ? "dependency needs" : "dependencies need"} review:`);
    lines.push("");
    for (const c of v) {
      const license = c.entry.license === "" ? "(none)" : c.entry.license;
      lines.push(`- \`${c.entry.name}@${c.entry.version}\` — ${license} (${c.status})`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

function summarize(classified: Classified[]): string {
  const v = violations(classified);
  const items =
    v.length === 0
      ? ["- No flagged licenses."]
      : v.map((c) => `- \`${c.entry.name}@${c.entry.version}\` — ${c.entry.license || "(none)"} (${c.status})`);
  return [
    "## License report",
    "",
    "Dependency licenses flagged against the allowlist:",
    ...items,
    "",
    "_Generated by loopy license-sbom-drift. Review flagged licenses; grant exceptions or replace deps._",
  ].join("\n");
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type { SbomEntry, SbomSource, LicenseStatus, Classified } from "./hooks/licenses.js";
