import type {
  ActResult,
  DetectResult,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import { findGaps, type CoverageProvider } from "./hooks/coverage.js";
import type { TestGenerator, Validator } from "./hooks/generate.js";

export interface TestCoverageServices {
  coverage: CoverageProvider;
  generator: TestGenerator;
  validate: Validator;
}

/**
 * Test-coverage backfill loop. Finds changed lines lacking coverage, asks an AI
 * step to generate tests, and proposes them only when they pass and raise
 * coverage (self-validating, fail-safe).
 */
export function createTestCoverageLoop(
  guardrails: Guardrails,
  trigger: Trigger,
  services: TestCoverageServices,
): Loop {
  async function gaps() {
    const [uncovered, changed] = await Promise.all([
      services.coverage.getUncovered(),
      services.coverage.getChangedLines(),
    ]);
    return findGaps(uncovered, changed);
  }

  return {
    id: "test-coverage",
    trigger,
    guardrails,

    async detect(ctx: RunContext): Promise<DetectResult> {
      void ctx;
      const found = await gaps();
      if (found.length === 0) {
        return { workNeeded: false, reason: "no coverage gaps on changed lines" };
      }
      return {
        workNeeded: true,
        reason: `${found.length} file(s) with uncovered changed lines`,
        affected: found.map((g) => g.file),
      };
    },

    async act(ctx: RunContext): Promise<ActResult> {
      void ctx;
      const found = await gaps();
      const changes = await services.generator(found);
      if (changes.length === 0) {
        return { changes: [], summary: "no tests generated" };
      }

      const validation = await services.validate(changes);
      if (!validation.passed || !validation.coverageRose) {
        // Fail safe: do not propose tests that fail or don't help.
        return {
          changes: [],
          summary: `generated tests rejected (passed=${validation.passed}, coverageRose=${validation.coverageRose})`,
        };
      }

      return {
        changes,
        summary: [
          "## Test coverage backfill",
          "",
          `Added tests covering ${found.length} file(s) with previously uncovered changed lines.`,
          "",
          "Validated: suite passes and coverage increased.",
          "",
          "_Generated by loopy test-coverage. Review assertions before merging._",
        ].join("\n"),
      };
    },
  };
}

export function createTestCoverageLoopFromManifest(
  manifest: LoopManifest,
  services: TestCoverageServices,
): Loop {
  return createTestCoverageLoop(manifest.guardrails, manifest.trigger, services);
}

export { findGaps } from "./hooks/coverage.js";
export type { CoverageProvider, CoverageGap } from "./hooks/coverage.js";
export type { TestGenerator, Validator, ValidationResult } from "./hooks/generate.js";
