export interface ApiDeprecationSpec {
  api: string;
  noticePath: string;
  removalPath: string;
  graceUntilIso: string;
}

/** Telemetry boundary: how many callers still use the API. */
export interface ApiDeprecationServices {
  remainingCallers(): Promise<number>;
}

/** Deterministic markdown deprecation notice mentioning the api and grace deadline. */
export function renderDeprecationNotice(api: string, graceUntilIso: string): string {
  return [
    `## Deprecation notice: \`${api}\``,
    "",
    `The \`${api}\` API is **deprecated** and scheduled for removal.`,
    "",
    `- Grace period ends: ${graceUntilIso}`,
    `- Migrate off \`${api}\` before the deadline; calls after removal will fail.`,
    "",
    "_Generated by loopy api-deprecation-rollout. Removal is human-gated._",
  ].join("\n");
}

/** Deterministic markdown note that the api is being removed. */
export function renderRemovalNote(api: string): string {
  return [
    `## Removal: \`${api}\``,
    "",
    `The \`${api}\` API has been **removed**. All callers were drained and the`,
    "removal was approved at the human gate.",
    "",
    "_Generated by loopy api-deprecation-rollout._",
  ].join("\n");
}
