import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import {
  diffSurface,
  fingerprintSurface,
  readMarker,
  type Fingerprint,
} from "./hooks/fingerprint.js";
import { resolveFiles } from "./hooks/surface.js";

export interface AutoDocsConfig {
  /** globs describing the code surface whose changes trigger doc updates */
  codeSurface: string[];
  /** docs the loop is allowed to write */
  docTargets: string[];
  /** marker file storing the last-synced code-surface fingerprint */
  markerPath: string;
}

export interface DocWriterInput {
  repoRoot: string;
  changedSurface: string[];
  docTargets: string[];
  previous: Fingerprint | null;
  current: Fingerprint;
}

export interface DocChange {
  path: string;
  contents: string;
}

/**
 * The AI step (driven by `playbook.md`): given the drift context, return the
 * updated contents of any docs that need changing. This is the loop's only
 * provider-specific boundary; everything else is deterministic.
 */
export type DocWriter = (input: DocWriterInput) => Promise<DocChange[]>;

export interface AutoDocsServices {
  docWriter: DocWriter;
}

/** Build the auto-docs loop from explicit config + the injected services. */
export function createAutoDocsLoop(
  config: AutoDocsConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: AutoDocsServices,
): Loop {
  return {
    id: "auto-docs",
    trigger,
    guardrails,

    async detect(ctx: RunContext): Promise<DetectResult> {
      const current = await fingerprint(ctx.repoRoot, config);
      const previous = await readMarker(ctx.repoRoot, config.markerPath);
      if (!previous) {
        return { workNeeded: true, reason: "no marker yet (first run)", affected: config.docTargets };
      }
      if (previous.digest === current.digest) {
        return { workNeeded: false, reason: "code surface unchanged" };
      }
      return {
        workNeeded: true,
        reason: "code surface drifted from docs",
        affected: diffSurface(previous, current),
      };
    },

    async act(ctx: RunContext, detected: DetectResult): Promise<ActResult> {
      const current = await fingerprint(ctx.repoRoot, config);
      const previous = await readMarker(ctx.repoRoot, config.markerPath);

      const docChanges = await services.docWriter({
        repoRoot: ctx.repoRoot,
        changedSurface: detected.affected ?? [],
        docTargets: config.docTargets,
        previous,
        current,
      });

      const changes: FileChange[] = docChanges.map((d) => ({
        path: d.path,
        op: "write",
        contents: d.contents,
      }));

      // Persist the new fingerprint so the next run is idempotent (no drift => no PR).
      changes.push({
        path: config.markerPath,
        op: "write",
        contents: JSON.stringify(current, null, 2) + "\n",
      });

      return { changes, summary: summarize(detected, docChanges) };
    },
  };
}

/** Build the auto-docs loop from a parsed `loop.yaml` manifest. */
export function createAutoDocsLoopFromManifest(
  manifest: LoopManifest,
  services: AutoDocsServices,
): Loop {
  const c = manifest.config;
  const config: AutoDocsConfig = {
    codeSurface: asStringArray(c["codeSurface"], ["src/**/*.ts"]),
    docTargets: asStringArray(c["docTargets"], ["README.md", "docs/**/*.md"]),
    markerPath:
      typeof c["markerPath"] === "string" ? c["markerPath"] : "docs/.loopy-auto-docs.json",
  };
  return createAutoDocsLoop(config, manifest.guardrails, manifest.trigger, services);
}

async function fingerprint(repoRoot: string, config: AutoDocsConfig): Promise<Fingerprint> {
  const files = await resolveFiles(repoRoot, config.codeSurface);
  return fingerprintSurface(repoRoot, files);
}

function asStringArray(value: unknown, fallback: string[]): string[] {
  return Array.isArray(value) && value.length > 0 ? value.map(String) : fallback;
}

function summarize(detected: DetectResult, docChanges: DocChange[]): string {
  const docLines =
    docChanges.length > 0
      ? docChanges.map((d) => `- \`${d.path}\``)
      : ["- _(no doc files changed)_"];
  return [
    "## Auto-docs update",
    "",
    detected.reason ? `Reason: ${detected.reason}.` : "",
    "",
    "Updated documentation:",
    ...docLines,
    "",
    "_Generated by loopy auto-docs. Review for accuracy before merging._",
  ]
    .filter((line, i, arr) => !(line === "" && arr[i - 1] === ""))
    .join("\n");
}

export type { Fingerprint } from "./hooks/fingerprint.js";
