import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  Trigger,
} from "../../src/core/index.js";
import {
  findOverdue,
  findRecurrences,
  type IncidentSource,
  type OverdueItem,
  type Recurrence,
} from "./hooks/incidents.js";

export interface IncidentFollowupConfig {
  /** path the follow-up digest is written to (default "reports/incident-followup.md") */
  reportPath: string;
  /** incidents sharing a root cause before it counts as a recurrence (default 2) */
  minRecurrence: number;
}

export interface IncidentFollowupServices {
  incidents: IncidentSource;
  /** injectable clock for deterministic runs (default `new Date`) */
  now?: () => Date;
}

interface Findings {
  nowIso: string;
  overdue: OverdueItem[];
  recurrences: Recurrence[];
}

/** Build the incident-followup loop from explicit config + the injected services. */
export function createIncidentFollowupLoop(
  config: IncidentFollowupConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: IncidentFollowupServices,
): Loop {
  async function computeFindings(): Promise<Findings> {
    const nowIso = (services.now?.() ?? new Date()).toISOString();
    const overdue = findOverdue(await services.incidents.actionItems(), nowIso);
    const recurrences = findRecurrences(await services.incidents.incidents(), config.minRecurrence);
    return { nowIso, overdue, recurrences };
  }

  return {
    id: "incident-followup",
    trigger,
    guardrails,

    async detect(): Promise<DetectResult> {
      const { overdue, recurrences } = await computeFindings();
      if (overdue.length === 0 && recurrences.length === 0) {
        return { workNeeded: false, reason: "no overdue action items or recurring root causes" };
      }
      return {
        workNeeded: true,
        reason: `${overdue.length} overdue item(s), ${recurrences.length} recurring cause(s)`,
        affected: [...overdue.map((o) => o.item.id), ...recurrences.map((r) => r.rootCause)],
      };
    },

    async act(): Promise<ActResult> {
      const { nowIso, overdue, recurrences } = await computeFindings();
      const dateIso = nowIso.slice(0, 10);
      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderDigest(overdue, recurrences, dateIso),
      };
      return { changes: [change], summary: summarize(overdue, recurrences, config.reportPath) };
    },
  };
}

/** Build the incident-followup loop from a parsed `loop.yaml` manifest. */
export function createIncidentFollowupLoopFromManifest(
  manifest: LoopManifest,
  services: IncidentFollowupServices,
): Loop {
  const c = manifest.config;
  const config: IncidentFollowupConfig = {
    reportPath:
      typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/incident-followup.md",
    minRecurrence: typeof c["minRecurrence"] === "number" ? c["minRecurrence"] : 2,
  };
  return createIncidentFollowupLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the markdown follow-up digest. */
export function renderDigest(
  overdue: OverdueItem[],
  recurrences: Recurrence[],
  dateIso: string,
): string {
  const lines: string[] = [`# Incident follow-up — ${dateIso}`, ""];

  lines.push("## Overdue action items", "");
  if (overdue.length === 0) {
    lines.push("None — all open action items are on track.", "");
  } else {
    lines.push("| Days overdue | Item | Incident |", "|---|---|---|");
    for (const o of overdue) {
      lines.push(`| ${o.daysOverdue} | ${o.item.title} | ${o.item.incidentId} |`);
    }
    lines.push("");
  }

  lines.push("## Recurring root causes", "");
  if (recurrences.length === 0) {
    lines.push("None — no root cause met the recurrence threshold.", "");
  } else {
    lines.push("| Count | Root cause | Incidents |", "|---|---|---|");
    for (const r of recurrences) {
      lines.push(`| ${r.count} | ${r.rootCause} | ${r.incidentIds.join(", ")} |`);
    }
    lines.push("");
  }

  lines.push("_Generated by loopy incident-followup. Review and assign owners._");
  return lines.join("\n");
}

function summarize(overdue: OverdueItem[], recurrences: Recurrence[], reportPath: string): string {
  return [
    "## Incident follow-up",
    "",
    `- ${overdue.length} overdue action item(s)`,
    `- ${recurrences.length} recurring root cause(s)`,
    `- digest: \`${reportPath}\``,
    "",
    "_Generated by loopy incident-followup. Review and assign owners._",
  ].join("\n");
}

export type {
  ActionItem,
  Incident,
  IncidentSource,
  OverdueItem,
  Recurrence,
} from "./hooks/incidents.js";
export { findOverdue, findRecurrences, normalizeCause } from "./hooks/incidents.js";
