import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ActResult,
  DetectResult,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import type { CommitProvider } from "./hooks/commits.js";
import { renderChangelogEntry } from "./hooks/conventional.js";

export interface ChangelogConfig {
  /** path to the changelog file (default "CHANGELOG.md") */
  changelogPath: string;
}

export interface ChangelogServices {
  commits: CommitProvider;
  /** override for the entry date (primarily for tests); defaults to today */
  now?: () => Date;
}

const HEADER = "# Changelog\n";

export function createChangelogLoop(
  config: ChangelogConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: ChangelogServices,
): Loop {
  const today = () => (services.now ? services.now() : new Date()).toISOString().slice(0, 10);

  return {
    id: "changelog",
    trigger,
    guardrails,

    async detect(ctx: RunContext): Promise<DetectResult> {
      void ctx;
      const commits = await services.commits.listUnreleased();
      if (commits.length === 0) {
        return { workNeeded: false, reason: "no unreleased commits" };
      }
      return {
        workNeeded: true,
        reason: `${commits.length} unreleased commit(s)`,
        affected: [config.changelogPath],
      };
    },

    async act(ctx: RunContext): Promise<ActResult> {
      const commits = await services.commits.listUnreleased();
      const label = await services.commits.nextVersionLabel();
      const entry = renderChangelogEntry(label, today(), commits);

      const existing = await readExisting(ctx.repoRoot, config.changelogPath);
      const contents = prepend(existing, entry);

      return {
        changes: [{ path: config.changelogPath, op: "write", contents }],
        summary: `## Changelog updated\n\nAdded an entry for **${label}** with ${commits.length} commit(s).\n\n_Generated by loopy changelog. Review before merging._`,
      };
    },
  };
}

export function createChangelogLoopFromManifest(
  manifest: LoopManifest,
  services: ChangelogServices,
): Loop {
  const c = manifest.config;
  const config: ChangelogConfig = {
    changelogPath:
      typeof c["changelogPath"] === "string" ? c["changelogPath"] : "CHANGELOG.md",
  };
  return createChangelogLoop(config, manifest.guardrails, manifest.trigger, services);
}

async function readExisting(repoRoot: string, path: string): Promise<string | null> {
  try {
    return await readFile(join(repoRoot, path), "utf8");
  } catch {
    return null;
  }
}

/** Insert the entry after the top-level header, preserving prior entries. */
function prepend(existing: string | null, entry: string): string {
  if (!existing || existing.trim().length === 0) {
    return `${HEADER}\n${entry}\n`;
  }
  const lines = existing.split("\n");
  const headerIdx = lines.findIndex((l) => l.startsWith("# "));
  if (headerIdx === -1) {
    return `${HEADER}\n${entry}\n\n${existing.trimStart()}`;
  }
  const before = lines.slice(0, headerIdx + 1).join("\n");
  const after = lines.slice(headerIdx + 1).join("\n").replace(/^\n+/, "");
  return `${before}\n\n${entry}\n\n${after}`.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

export type { CommitProvider } from "./hooks/commits.js";
export type { Commit } from "./hooks/conventional.js";
export { createGitCommitProvider } from "./hooks/commits.js";
