import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import { detectAnomalies, type Anomaly, type MetricSource } from "./hooks/anomaly.js";

export interface MetricAnomalyConfig {
  /** path the anomaly brief is written to (default "reports/anomalies.md") */
  reportPath: string;
  /** z-score magnitude at/above which a final point counts as anomalous (default 3) */
  zThreshold: number;
}

export interface MetricAnomalyServices {
  metrics: MetricSource;
  /** clock boundary, injectable for deterministic output (default `new Date`) */
  now?: () => Date;
}

/** Build the metric-anomaly loop from explicit config + the injected services. */
export function createMetricAnomalyLoop(
  config: MetricAnomalyConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: MetricAnomalyServices,
): Loop {
  async function computeAnomalies(): Promise<Anomaly[]> {
    const series = await services.metrics.series();
    return detectAnomalies(series, config.zThreshold);
  }

  return {
    id: "metric-anomaly",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const anomalies = await computeAnomalies();
      if (anomalies.length === 0) {
        return { workNeeded: false, reason: "no metric anomalies" };
      }
      const n = anomalies.length;
      return {
        workNeeded: true,
        reason: `${n} ${n === 1 ? "anomaly" : "anomalies"}`,
        affected: anomalies.map((a) => a.metric),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      const anomalies = await computeAnomalies();
      const date = isoDate((services.now ?? (() => new Date()))());

      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderAnomalyBrief(anomalies, date),
      };

      return { changes: [change], summary: summarize(anomalies) };
    },
  };
}

/** Build the metric-anomaly loop from a parsed `loop.yaml` manifest. */
export function createMetricAnomalyLoopFromManifest(
  manifest: LoopManifest,
  services: MetricAnomalyServices,
): Loop {
  const c = manifest.config;
  const config: MetricAnomalyConfig = {
    reportPath: typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/anomalies.md",
    zThreshold: typeof c["zThreshold"] === "number" ? c["zThreshold"] : 3,
  };
  return createMetricAnomalyLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the anomaly brief as markdown. Numbers are rounded for display only. */
export function renderAnomalyBrief(anomalies: Anomaly[], dateIso: string): string {
  const lines: string[] = [`# Metric anomaly brief — ${dateIso}`, ""];

  if (anomalies.length === 0) {
    lines.push("No anomalies detected against each series' own baseline.");
    lines.push("");
    return lines.join("\n");
  }

  const n = anomalies.length;
  lines.push(`${n} ${n === 1 ? "metric" : "metrics"} drifted from baseline:`);
  lines.push("");
  lines.push("| Metric | Direction | Latest | Baseline mean | Baseline std | z-score |");
  lines.push("|--------|-----------|--------|---------------|--------------|---------|");
  for (const a of anomalies) {
    const arrow = a.direction === "up" ? "up" : "down";
    lines.push(
      `| ${a.metric} | ${arrow} | ${round(a.value)} | ${round(a.mean)} | ${round(a.std)} | ${round(a.z)} |`,
    );
  }
  lines.push("");

  return lines.join("\n");
}

function summarize(anomalies: Anomaly[]): string {
  const items = anomalies.map(
    (a) => `- \`${a.metric}\` ${a.direction} (z ${round(a.z)})`,
  );
  return [
    "## Metric anomaly brief",
    "",
    "Detected anomalies against each metric series' own baseline:",
    ...items,
    "",
    "_Generated by loopy metric-anomaly. Review before acting; metrics can be noisy._",
  ].join("\n");
}

/** Round to a few decimals for display, never in the returned anomaly numbers. */
function round(n: number): number {
  return Math.round(n * 1000) / 1000;
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type { Anomaly, MetricPoint, MetricSeries, MetricSource } from "./hooks/anomaly.js";
export { detectAnomalies } from "./hooks/anomaly.js";
