import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import { regressions, type Measurer, type Regression } from "./hooks/perf.js";

export interface PerfConfig {
  /** path the perf report is written to (default "reports/perf.md") */
  reportPath: string;
  /** fractional margin a measured value may exceed its baseline before it regresses (default 0.1) */
  tolerance: number;
}

export interface PerfServices {
  measurer: Measurer;
  /** baseline boundary: the stored per-metric baseline values to compare against */
  readBaseline: () => Promise<Record<string, number>>;
  /** clock boundary, injectable for deterministic output (default `new Date`) */
  now?: () => Date;
}

/** Build the perf-budget loop from explicit config + the injected services. */
export function createPerfBudgetLoop(
  config: PerfConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: PerfServices,
): Loop {
  async function computeRegressions(): Promise<Regression[]> {
    const current = await services.measurer.current();
    const baseline = await services.readBaseline();
    return regressions(current, baseline, config.tolerance);
  }

  return {
    id: "perf-budget",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const regs = await computeRegressions();
      if (regs.length === 0) {
        return { workNeeded: false, reason: "all metrics within budget" };
      }
      const n = regs.length;
      return {
        workNeeded: true,
        reason: `${n} ${n === 1 ? "regression" : "regressions"}`,
        affected: regs.map((r) => r.name),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      const regs = await computeRegressions();
      const date = isoDate((services.now ?? (() => new Date()))());

      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderPerfReport(regs, date),
      };

      return { changes: [change], summary: summarize(regs) };
    },
  };
}

/** Build the perf-budget loop from a parsed `loop.yaml` manifest. */
export function createPerfBudgetLoopFromManifest(
  manifest: LoopManifest,
  services: PerfServices,
): Loop {
  const c = manifest.config;
  const config: PerfConfig = {
    reportPath: typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/perf.md",
    tolerance: typeof c["tolerance"] === "number" ? c["tolerance"] : 0.1,
  };
  return createPerfBudgetLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the perf-budget report as markdown. */
export function renderPerfReport(regs: Regression[], dateIso: string): string {
  const lines: string[] = [`# Perf budget report — ${dateIso}`, ""];

  if (regs.length === 0) {
    lines.push("All measured metrics are within budget against the baseline.");
    lines.push("");
    return lines.join("\n");
  }

  const n = regs.length;
  lines.push(`${n} ${n === 1 ? "metric" : "metrics"} exceeded budget:`);
  lines.push("");
  lines.push("| Metric | Value | Baseline | Δ |");
  lines.push("|--------|-------|----------|---|");
  for (const r of regs) {
    lines.push(`| ${r.name} | ${r.value} | ${r.baseline} | +${r.pct}% |`);
  }
  lines.push("");

  return lines.join("\n");
}

function summarize(regs: Regression[]): string {
  const items = regs.map(
    (r) => `- \`${r.name}\`: ${r.value} (baseline ${r.baseline}, +${r.pct}%)`,
  );
  return [
    "## Perf budget report",
    "",
    "Metrics that regressed past their baseline budget:",
    ...items,
    "",
    "_Generated by loopy perf-budget. Investigate regressions or ratchet the baseline._",
  ].join("\n");
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type { Metric, Measurer, Regression } from "./hooks/perf.js";
export { regressions } from "./hooks/perf.js";
