import type { FileChange } from "../../../src/core/index.js";

/** Pure transform over the given files; returns the file changes to apply. */
export type Codemod = (files: string[]) => Promise<FileChange[]>;

/** Supplies the files that still match the campaign's "needs transform" predicate. */
export interface TargetSource {
  targets(): Promise<string[]>;
}

/** Runs the project's tests/build after a batch is applied. */
export type TestRunner = () => Promise<{ ok: boolean; diagnostics?: string }>;

export type PrState = "open" | "merged" | "closed";

/** The PR operations a campaign needs (create batch PRs; read their state). */
export interface CampaignPrs {
  state(prNumber: number): Promise<PrState>;
  open(input: {
    branch: string;
    title: string;
    body: string;
    changes: FileChange[];
  }): Promise<{ number: number }>;
}

export interface OpenBatch {
  prNumber: number;
  branch: string;
  files: string[];
}

/** Durable campaign ledger, persisted in the StateStore across runs. */
export interface CampaignLedger {
  migrated: string[];
  open: OpenBatch[];
  mergedBatches: number;
  failedBatches: number;
  batchesOpened: number;
  pilotApproved: boolean;
}

export interface CampaignSpec {
  /** files per batch PR */
  batchSize: number;
  /** maximum concurrent open batch PRs (throttle) */
  maxOpenPrs: number;
  /** PR title prefix */
  title: string;
}

export function emptyLedger(): CampaignLedger {
  return {
    migrated: [],
    open: [],
    mergedBatches: 0,
    failedBatches: 0,
    batchesOpened: 0,
    pilotApproved: false,
  };
}

/** Files still needing work: not migrated and not already in an open batch. */
export function remainingTargets(all: string[], ledger: CampaignLedger): string[] {
  const done = new Set(ledger.migrated);
  const inFlight = new Set(ledger.open.flatMap((b) => b.files));
  return all.filter((f) => !done.has(f) && !inFlight.has(f)).sort();
}

export function selectBatch(remaining: string[], batchSize: number): string[] {
  return remaining.slice(0, Math.max(1, batchSize));
}

/**
 * Reconcile the ledger against real PR state: merged batches' files become
 * migrated; closed batches are dropped (their files return to the pool); open
 * batches stay. External PR state is the source of truth.
 */
export async function reconcile(
  ledger: CampaignLedger,
  prs: CampaignPrs,
): Promise<CampaignLedger> {
  const stillOpen: OpenBatch[] = [];
  const migrated = new Set(ledger.migrated);
  let mergedBatches = ledger.mergedBatches;

  for (const batch of ledger.open) {
    const state = await prs.state(batch.prNumber);
    if (state === "merged") {
      for (const f of batch.files) migrated.add(f);
      mergedBatches++;
    } else if (state === "open") {
      stillOpen.push(batch);
    }
    // "closed" → drop; files return to the pool to be retried later.
  }

  return { ...ledger, migrated: [...migrated].sort(), open: stillOpen, mergedBatches };
}

/** Total targets across the campaign's lifetime (migrated + in-flight + remaining). */
export function campaignTotal(all: string[], ledger: CampaignLedger): number {
  const inFlight = ledger.open.reduce((n, b) => n + b.files.length, 0);
  return ledger.migrated.length + inFlight + remainingTargets(all, ledger).length;
}

export function renderBurndown(
  all: string[],
  ledger: CampaignLedger,
  dateIso: string,
): string {
  const total = campaignTotal(all, ledger);
  const remaining = remainingTargets(all, ledger).length;
  const inFlight = ledger.open.reduce((n, b) => n + b.files.length, 0);
  const pct = total > 0 ? Math.round((ledger.migrated.length / total) * 100) : 100;
  return [
    `## Codemod campaign burndown — ${dateIso}`,
    "",
    `- Progress: **${ledger.migrated.length}/${total}** files migrated (${pct}%)`,
    `- In flight: ${inFlight} file(s) across ${ledger.open.length} open PR(s)`,
    `- Remaining: ${remaining} file(s)`,
    `- Batches: ${ledger.batchesOpened} opened · ${ledger.mergedBatches} merged · ${ledger.failedBatches} failed`,
    "",
    "_Generated by loopy codemod-campaign. Throttled + ledger-tracked; pilot batch is human-gated._",
  ].join("\n");
}
