export interface DepMajorSpec {
  pkg: string;
  fromVersion: string;
  toVersion: string;
  manifestPath: string;
}

export interface VerifyResult {
  ok: boolean;
  log: string;
}

/** Builds/tests the consumer against the candidate version (the verification boundary). */
export interface DepMajorServices {
  verify(pkg: string, version: string): Promise<VerifyResult>;
}

/**
 * Pure helper: parse a package.json string and pin `pkg` to `^${toVersion}` in
 * `dependencies` (and in `devDependencies` if the entry already exists there).
 * Only existing entries are touched; `dependencies` is the default target.
 * Everything else is preserved. Returns pretty-printed JSON with a trailing newline.
 */
export function bumpManifest(manifestJson: string, pkg: string, toVersion: string): string {
  const obj = JSON.parse(manifestJson) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
    [key: string]: unknown;
  };
  const pinned = `^${toVersion}`;
  if (obj.dependencies && pkg in obj.dependencies) {
    obj.dependencies[pkg] = pinned;
  }
  if (obj.devDependencies && pkg in obj.devDependencies) {
    obj.devDependencies[pkg] = pinned;
  }
  return JSON.stringify(obj, null, 2) + "\n";
}

/** Deterministic markdown summary of the proposed bump and whether verification passed. */
export function renderMigrationReport(spec: DepMajorSpec, result: VerifyResult): string {
  return [
    `## Major dependency migration: \`${spec.pkg}\` ${spec.fromVersion} → ${spec.toVersion}`,
    "",
    `- Manifest: \`${spec.manifestPath}\``,
    `- Verification: ${result.ok ? "passed ✅" : "failed ❌"}`,
    "",
    "### Verification log",
    "",
    "```",
    result.log,
    "```",
    "",
    "_Generated by loopy dep-major-migration. The bump is human-gated and only proposed on a green build._",
  ].join("\n");
}
