import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  StateStore,
  Trigger,
} from "../../src/core/index.js";
import {
  regressions,
  updateBaseline,
  type Baseline,
  type Regression,
  type TimingSource,
} from "./hooks/timing.js";

const BASELINE_KEY = "test-impact:baseline";

export interface TestImpactConfig {
  /** path the test-impact report is written to (default "reports/test-impact.md") */
  reportPath: string;
  /** fractional growth over baseline a test may exceed before it regresses (default 0.5) */
  growthThreshold: number;
  /** EWMA smoothing factor used to roll the baseline forward (default 0.3) */
  alpha: number;
}

export interface TestImpactServices {
  /** timing boundary: supplies the latest per-test durations */
  timings: TimingSource;
  /** durable EWMA baseline across runs */
  state: StateStore;
}

/** Build the test-impact-budget loop from explicit config + the injected services. */
export function createTestImpactBudgetLoop(
  config: TestImpactConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: TestImpactServices,
): Loop {
  async function loadBaseline(): Promise<Baseline> {
    return (await services.state.load<Baseline>(BASELINE_KEY)) ?? {};
  }

  return {
    id: "test-impact-budget",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const baseline = await loadBaseline();
      const latest = await services.timings.latest();
      const regs = regressions(latest, baseline, config.growthThreshold);
      if (regs.length === 0) {
        return { workNeeded: false, reason: "all tests within their runtime budget" };
      }
      const n = regs.length;
      return {
        workNeeded: true,
        reason: `${n} ${n === 1 ? "test regression" : "test regressions"}`,
        affected: regs.map((r) => r.testId),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      // Regressions are computed against the OLD baseline...
      const baseline = await loadBaseline();
      const latest = await services.timings.latest();
      const regs = regressions(latest, baseline, config.growthThreshold);

      // ...then the baseline is rolled forward and persisted for the next run.
      await services.state.save<Baseline>(BASELINE_KEY, updateBaseline(baseline, latest, config.alpha));

      const dateIso = new Date().toISOString().slice(0, 10);
      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderTimingReport(regs, dateIso),
      };

      return { changes: [change], summary: summarize(regs) };
    },
  };
}

/** Build the test-impact-budget loop from a parsed `loop.yaml` manifest. */
export function createTestImpactBudgetLoopFromManifest(
  manifest: LoopManifest,
  services: TestImpactServices,
): Loop {
  const c = manifest.config;
  const config: TestImpactConfig = {
    reportPath: typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/test-impact.md",
    growthThreshold: typeof c["growthThreshold"] === "number" ? c["growthThreshold"] : 0.5,
    alpha: typeof c["alpha"] === "number" ? c["alpha"] : 0.3,
  };
  return createTestImpactBudgetLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the test-impact report as markdown, slowest-relative-growth first. */
export function renderTimingReport(regs: Regression[], dateIso: string): string {
  const lines: string[] = [`# Test impact budget report — ${dateIso}`, ""];

  if (regs.length === 0) {
    lines.push("All tracked tests are within their runtime budget against the baseline.");
    lines.push("");
    return lines.join("\n");
  }

  const n = regs.length;
  lines.push(`${n} ${n === 1 ? "test" : "tests"} grew past their runtime budget:`);
  lines.push("");
  lines.push("| Test | Duration (ms) | Baseline (ms) | Δ |");
  lines.push("|------|---------------|---------------|---|");
  for (const r of regs) {
    lines.push(`| \`${r.testId}\` | ${r.durationMs} | ${r.baselineMs} | +${r.pct}% |`);
  }
  lines.push("");

  return lines.join("\n");
}

function summarize(regs: Regression[]): string {
  const items = regs.map(
    (r) => `- \`${r.testId}\`: ${r.durationMs}ms (baseline ${r.baselineMs}ms, +${r.pct}%)`,
  );
  return [
    "## Test impact budget report",
    "",
    "Tests whose runtime grew past their rolling baseline:",
    ...items,
    "",
    "_Generated by loopy test-impact-budget. Investigate the slowdown or accept the new baseline._",
  ].join("\n");
}

export type { TestTiming, TimingSource, Baseline, Regression } from "./hooks/timing.js";
export { regressions, updateBaseline } from "./hooks/timing.js";
