import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import { computeDrift, type LocaleDrift, type LocaleSource } from "./hooks/i18n.js";

export interface I18nConfig {
  /** path the i18n status report is written to (default "reports/i18n-status.md") */
  reportPath: string;
}

export interface I18nServices {
  source: LocaleSource;
}

/** Build the i18n-drift loop from explicit config + the injected services. */
export function createI18nDriftLoop(
  config: I18nConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: I18nServices,
): Loop {
  async function load(): Promise<{ defaultKeys: string[]; drift: LocaleDrift[] }> {
    const defaultKeys = await services.source.defaultKeys();
    const locales = await services.source.locales();
    return { defaultKeys, drift: computeDrift(defaultKeys, locales) };
  }

  return {
    id: "i18n-drift",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const { drift } = await load();
      if (drift.length === 0) {
        return { workNeeded: false, reason: "all locales in sync with the default" };
      }
      const n = drift.length;
      return {
        workNeeded: true,
        reason: `${n} ${n === 1 ? "locale" : "locales"} drifted`,
        affected: drift.map((d) => d.locale),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      const { defaultKeys, drift } = await load();
      const date = isoDate(new Date());

      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderI18nReport(drift, defaultKeys.length, date),
      };

      return { changes: [change], summary: summarize(drift) };
    },
  };
}

/** Build the i18n-drift loop from a parsed `loop.yaml` manifest. */
export function createI18nDriftLoopFromManifest(
  manifest: LoopManifest,
  services: I18nServices,
): Loop {
  const c = manifest.config;
  const config: I18nConfig = {
    reportPath:
      typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/i18n-status.md",
  };
  return createI18nDriftLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the i18n status report as markdown. */
export function renderI18nReport(
  drift: LocaleDrift[],
  totalDefault: number,
  dateIso: string,
): string {
  const lines: string[] = [`# i18n status report — ${dateIso}`, ""];
  lines.push(`Default locale defines ${totalDefault} key(s).`);
  lines.push("");

  if (drift.length === 0) {
    lines.push("All locales are in sync with the default locale.");
    lines.push("");
    return lines.join("\n");
  }

  const n = drift.length;
  lines.push(`${n} ${n === 1 ? "locale" : "locales"} drifted from the default:`);
  lines.push("");
  lines.push("| Locale | Missing | Orphaned |");
  lines.push("|--------|---------|----------|");
  for (const d of drift) {
    lines.push(`| ${d.locale} | ${d.missing.length} | ${d.orphaned.length} |`);
  }
  lines.push("");

  for (const d of drift) {
    lines.push(`## ${d.locale}`);
    lines.push("");
    if (d.missing.length > 0) {
      lines.push(`Missing (${d.missing.length}):`);
      for (const k of d.missing) lines.push(`- \`${k}\``);
      lines.push("");
    }
    if (d.orphaned.length > 0) {
      lines.push(`Orphaned (${d.orphaned.length}):`);
      for (const k of d.orphaned) lines.push(`- \`${k}\``);
      lines.push("");
    }
  }

  return lines.join("\n");
}

function summarize(drift: LocaleDrift[]): string {
  const items = drift.map(
    (d) =>
      `- \`${d.locale}\` — ${d.missing.length} missing, ${d.orphaned.length} orphaned`,
  );
  return [
    "## i18n status report",
    "",
    "Translation-key drift relative to the default locale:",
    ...items,
    "",
    "_Generated by loopy i18n-drift. Add/translate the missing keys; remove orphans._",
  ].join("\n");
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type { LocaleDrift, LocaleKeys, LocaleSource } from "./hooks/i18n.js";
export { computeDrift, findMissing, findOrphaned } from "./hooks/i18n.js";
