import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { RegistryClient } from "./registry.js";
import { formatRange, parseRange, parseVersion, updateType, type UpdateType } from "./semver.js";

export type DepSection = "dependencies" | "devDependencies";

export interface PendingUpdate {
  name: string;
  section: DepSection;
  from: string; // existing range, e.g. "^1.2.3"
  to: string; // proposed range, e.g. "^1.5.0"
  type: UpdateType;
}

export interface ComputeOptions {
  manifestPath: string;
  includeDev: boolean;
  allowMajor: boolean;
}

export interface ComputeResult {
  /** parsed manifest object (mutated copy with applied bumps) */
  manifest: Record<string, unknown>;
  /** non-major (or all, if allowMajor) updates that were applied */
  applied: PendingUpdate[];
  /** major updates that were detected but not applied */
  skippedMajor: PendingUpdate[];
}

type Manifest = Record<string, unknown> & {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
};

/**
 * Read the manifest, query the registry for each dependency, and compute the
 * set of updates. Applies non-major updates to a copy of the manifest (or all
 * updates when allowMajor is set); major updates are reported separately.
 *
 * Individual dependency failures (registry error, unparseable range) are
 * skipped rather than aborting the whole run.
 */
export async function computeUpdates(
  repoRoot: string,
  registry: RegistryClient,
  options: ComputeOptions,
): Promise<ComputeResult> {
  const manifest = JSON.parse(
    await readFile(join(repoRoot, options.manifestPath), "utf8"),
  ) as Manifest;

  const sections: DepSection[] = options.includeDev
    ? ["dependencies", "devDependencies"]
    : ["dependencies"];

  const applied: PendingUpdate[] = [];
  const skippedMajor: PendingUpdate[] = [];

  for (const section of sections) {
    const deps = manifest[section];
    if (!deps) continue;
    for (const [name, range] of Object.entries(deps)) {
      const parsed = parseRange(range);
      if (!parsed) continue;
      const latestStr = await registry.getLatest(name);
      if (!latestStr) continue;
      const latest = parseVersion(latestStr);
      if (!latest) continue;

      const type = updateType(parsed.version, latest);
      if (!type) continue;

      const update: PendingUpdate = {
        name,
        section,
        from: range,
        to: formatRange(parsed.prefix, latest),
        type,
      };

      if (type === "major" && !options.allowMajor) {
        skippedMajor.push(update);
        continue;
      }
      deps[name] = update.to;
      applied.push(update);
    }
  }

  return { manifest, applied, skippedMajor };
}

/** Render a PR/run summary from a compute result. */
export function summarizeUpdates(result: ComputeResult): string {
  const lines: string[] = ["## Dependency updates", ""];

  if (result.applied.length > 0) {
    lines.push("Applied:");
    for (const u of result.applied) {
      lines.push(`- \`${u.name}\`: ${u.from} → ${u.to} (${u.type})`);
    }
    lines.push("");
  }
  if (result.skippedMajor.length > 0) {
    lines.push("Major updates available (not applied — review manually):");
    for (const u of result.skippedMajor) {
      lines.push(`- \`${u.name}\`: ${u.from} → ${u.to}`);
    }
    lines.push("");
  }
  lines.push("_Generated by loopy dep-updates. Review and ensure CI is green before merging._");
  return lines.join("\n");
}
