import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import {
  computeBump,
  nextVersion,
  renderReleaseNotes,
  type ReleaseSource,
} from "./hooks/release.js";

export interface ReleaseTrainConfig {
  /** path to the package manifest whose version is bumped (default "package.json") */
  manifestPath: string;
  /** path to the changelog file the release notes are prepended to (default "CHANGELOG.md") */
  changelogPath: string;
}

export interface ReleaseTrainServices {
  source: ReleaseSource;
  /** override for the release date (primarily for tests); defaults to today */
  now?: () => Date;
}

const HEADER = "# Changelog\n";
const FOOTER = "_Generated by loopy release-train. Merge to cut the release._";

export function createReleaseTrainLoop(
  config: ReleaseTrainConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: ReleaseTrainServices,
): Loop {
  const today = () => (services.now ? services.now() : new Date()).toISOString().slice(0, 10);

  return {
    id: "release-train",
    trigger,
    guardrails,

    async detect(ctx: RunContext): Promise<DetectResult> {
      void ctx;
      const commits = await services.source.unreleased();
      const bump = computeBump(commits);
      if (bump === null) {
        return { workNeeded: false, reason: "no releasable commits" };
      }
      const current = await services.source.currentVersion();
      const next = nextVersion(current, bump);
      return {
        workNeeded: true,
        reason: `release ${next} (${bump})`,
        affected: [config.manifestPath, config.changelogPath],
      };
    },

    async act(ctx: RunContext): Promise<ActResult> {
      const commits = await services.source.unreleased();
      const bump = computeBump(commits);
      if (bump === null) {
        return { changes: [], summary: "No releasable commits; nothing to release." };
      }

      const current = await services.source.currentVersion();
      const next = nextVersion(current, bump);
      const date = today();

      const manifest = await readManifest(ctx.repoRoot, config.manifestPath);
      manifest.version = next;
      const manifestContents = JSON.stringify(manifest, null, 2) + "\n";

      const notes = renderReleaseNotes(next, date, commits);
      const existingChangelog = await readExisting(ctx.repoRoot, config.changelogPath);
      const changelogContents = prepend(existingChangelog, notes);

      const changes: FileChange[] = [
        { path: config.manifestPath, op: "write", contents: manifestContents },
        { path: config.changelogPath, op: "write", contents: changelogContents },
      ];

      return {
        changes,
        summary: `${notes}\n\n${FOOTER}`,
      };
    },
  };
}

export function createReleaseTrainLoopFromManifest(
  manifest: LoopManifest,
  services: ReleaseTrainServices,
): Loop {
  const c = manifest.config;
  const config: ReleaseTrainConfig = {
    manifestPath: typeof c["manifestPath"] === "string" ? c["manifestPath"] : "package.json",
    changelogPath: typeof c["changelogPath"] === "string" ? c["changelogPath"] : "CHANGELOG.md",
  };
  return createReleaseTrainLoop(config, manifest.guardrails, manifest.trigger, services);
}

async function readManifest(
  repoRoot: string,
  path: string,
): Promise<Record<string, unknown> & { version?: string }> {
  const raw = await readFile(join(repoRoot, path), "utf8");
  const parsed: unknown = JSON.parse(raw);
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error(`Manifest at ${path} is not a JSON object`);
  }
  return parsed as Record<string, unknown> & { version?: string };
}

async function readExisting(repoRoot: string, path: string): Promise<string> {
  try {
    return await readFile(join(repoRoot, path), "utf8");
  } catch {
    return "";
  }
}

/** Insert the notes after the top-level header (adding one if absent), newest on top. */
function prepend(existing: string, entry: string): string {
  if (existing.trim().length === 0) {
    return `${HEADER}\n${entry}\n`;
  }
  const lines = existing.split("\n");
  const headerIdx = lines.findIndex((l) => l.startsWith("# "));
  if (headerIdx === -1) {
    return `${HEADER}\n${entry}\n\n${existing.trimStart()}`
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n";
  }
  const before = lines.slice(0, headerIdx + 1).join("\n");
  const after = lines
    .slice(headerIdx + 1)
    .join("\n")
    .replace(/^\n+/, "");
  return `${before}\n\n${entry}\n\n${after}`.replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

export type { ReleaseSource, Bump } from "./hooks/release.js";
export type { Commit } from "./hooks/release.js";
export { computeBump, nextVersion, renderReleaseNotes } from "./hooks/release.js";
