import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  Trigger,
} from "../../src/core/index.js";
import {
  staleRunbooks,
  type RunbookSource,
  type StaleRunbook,
} from "./hooks/runbooks.js";

export interface RunbookConfig {
  /** path the health report is written to (default "reports/runbook-health.md") */
  reportPath: string;
  /** days since last review before a runbook counts as stale (default 90) */
  intervalDays: number;
}

export interface RunbookServices {
  source: RunbookSource;
  /** injectable clock for deterministic runs (default `new Date`) */
  now?: () => Date;
}

interface Findings {
  nowIso: string;
  stale: StaleRunbook[];
}

/** Build the runbook-freshness loop from explicit config + the injected services. */
export function createRunbookFreshnessLoop(
  config: RunbookConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: RunbookServices,
): Loop {
  async function computeFindings(): Promise<Findings> {
    const nowIso = (services.now?.() ?? new Date()).toISOString();
    const stale = staleRunbooks(await services.source.runbooks(), nowIso, config.intervalDays);
    return { nowIso, stale };
  }

  return {
    id: "runbook-freshness",
    trigger,
    guardrails,

    async detect(): Promise<DetectResult> {
      const { stale } = await computeFindings();
      if (stale.length === 0) {
        return { workNeeded: false, reason: "all runbooks reviewed within the interval" };
      }
      const n = stale.length;
      return {
        workNeeded: true,
        reason: `${n} stale runbook(s)`,
        affected: stale.map((s) => s.path),
      };
    },

    async act(): Promise<ActResult> {
      const { nowIso, stale } = await computeFindings();
      const dateIso = nowIso.slice(0, 10);
      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderRunbookReport(stale, dateIso),
      };
      return { changes: [change], summary: summarize(stale, config.reportPath) };
    },
  };
}

/** Build the runbook-freshness loop from a parsed `loop.yaml` manifest. */
export function createRunbookFreshnessLoopFromManifest(
  manifest: LoopManifest,
  services: RunbookServices,
): Loop {
  const c = manifest.config;
  const config: RunbookConfig = {
    reportPath:
      typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/runbook-health.md",
    intervalDays: typeof c["intervalDays"] === "number" ? c["intervalDays"] : 90,
  };
  return createRunbookFreshnessLoop(config, manifest.guardrails, manifest.trigger, services);
}

/** Render the runbook health report as markdown. */
export function renderRunbookReport(stale: StaleRunbook[], dateIso: string): string {
  const lines: string[] = [`# Runbook health — ${dateIso}`, ""];

  if (stale.length === 0) {
    lines.push("All runbooks have been reviewed within the interval.", "");
    lines.push(
      "_Generated by loopy runbook-freshness. Review the stale runbooks and stamp lastReviewed._",
    );
    return lines.join("\n");
  }

  const n = stale.length;
  lines.push(`${n} ${n === 1 ? "runbook" : "runbooks"} past the review interval:`, "");
  lines.push("| Days since review | Runbook |", "|---|---|");
  for (const s of stale) {
    lines.push(`| ${s.daysSinceReview} | ${s.path} |`);
  }
  lines.push("");
  lines.push(
    "_Generated by loopy runbook-freshness. Review the stale runbooks and stamp lastReviewed._",
  );
  return lines.join("\n");
}

function summarize(stale: StaleRunbook[], reportPath: string): string {
  const items = stale.map((s) => `- \`${s.path}\` (${s.daysSinceReview} days since review)`);
  return [
    "## Runbook health",
    "",
    `- ${stale.length} stale runbook(s)`,
    ...items,
    `- report: \`${reportPath}\``,
    "",
    "_Generated by loopy runbook-freshness. Review the stale runbooks and stamp lastReviewed._",
  ].join("\n");
}

export type { Runbook, RunbookSource, StaleRunbook } from "./hooks/runbooks.js";
export { staleRunbooks } from "./hooks/runbooks.js";
