import type {
  ActResult,
  DetectResult,
  FileChange,
  Guardrails,
  Loop,
  LoopManifest,
  RunContext,
  Trigger,
} from "../../src/core/index.js";
import {
  fixedViolations,
  newViolations,
  violationKey,
  type A11yScanner,
  type Violation,
} from "./hooks/a11y.js";

export interface A11yConfig {
  /** path the a11y report is written to (default "reports/a11y.md") */
  reportPath: string;
}

export interface A11yServices {
  /** the scan boundary; returns the current set of violations */
  scanner: A11yScanner;
  /** the baseline boundary; returns the accepted (debt) violations */
  readBaseline: () => Promise<Violation[]>;
  /** clock boundary, injectable for deterministic output (default `new Date`) */
  now?: () => Date;
}

/** Build the a11y-baseline loop from explicit config + the injected services. */
export function createA11yBaselineLoop(
  config: A11yConfig,
  guardrails: Guardrails,
  trigger: Trigger,
  services: A11yServices,
): Loop {
  async function diff(): Promise<{ newOnes: Violation[]; fixed: Violation[] }> {
    const [current, baseline] = await Promise.all([
      services.scanner.scan(),
      services.readBaseline(),
    ]);
    return {
      newOnes: newViolations(current, baseline),
      fixed: fixedViolations(current, baseline),
    };
  }

  return {
    id: "a11y-baseline",
    trigger,
    guardrails,

    async detect(_ctx: RunContext): Promise<DetectResult> {
      const { newOnes } = await diff();
      if (newOnes.length === 0) {
        return { workNeeded: false, reason: "no new accessibility violations" };
      }
      const n = newOnes.length;
      return {
        workNeeded: true,
        reason: `${n} new accessibility ${n === 1 ? "violation" : "violations"}`,
        affected: newOnes.map(violationKey),
      };
    },

    async act(_ctx: RunContext): Promise<ActResult> {
      const { newOnes, fixed } = await diff();
      const date = isoDate((services.now ?? (() => new Date()))());

      const change: FileChange = {
        path: config.reportPath,
        op: "write",
        contents: renderA11yReport(newOnes, fixed, date),
      };

      return { changes: [change], summary: summarize(newOnes, fixed) };
    },
  };
}

/** Build the a11y-baseline loop from a parsed `loop.yaml` manifest. */
export function createA11yBaselineLoopFromManifest(
  manifest: LoopManifest,
  services: A11yServices,
): Loop {
  const c = manifest.config;
  const config: A11yConfig = {
    reportPath: typeof c["reportPath"] === "string" ? c["reportPath"] : "reports/a11y.md",
  };
  return createA11yBaselineLoop(config, manifest.guardrails, manifest.trigger, services);
}

/**
 * Render the a11y report as markdown: the new violations that should block, plus
 * a resolved note for any baseline debt that has been fixed (and can be dropped).
 */
export function renderA11yReport(
  newOnes: Violation[],
  fixed: Violation[],
  dateIso: string,
): string {
  const lines: string[] = [`# Accessibility report — ${dateIso}`, ""];

  const n = newOnes.length;
  lines.push(`## ⚠ New violations`);
  lines.push("");
  if (n === 0) {
    lines.push("No new violations against the baseline.");
  } else {
    lines.push(`${n} new ${n === 1 ? "violation" : "violations"} not in the baseline:`);
    lines.push("");
    lines.push("| Rule | Selector | Impact |");
    lines.push("|------|----------|--------|");
    for (const v of newOnes) {
      lines.push(`| ${v.id} | \`${v.selector}\` | ${v.impact ?? "(none)"} |`);
    }
  }
  lines.push("");

  lines.push("## ✓ Resolved");
  lines.push("");
  if (fixed.length === 0) {
    lines.push("No baseline violations were resolved in this run.");
  } else {
    const f = fixed.length;
    lines.push(
      `${f} baseline ${f === 1 ? "violation has" : "violations have"} been resolved and can be removed from the baseline:`,
    );
    lines.push("");
    for (const v of fixed) {
      lines.push(`- \`${violationKey(v)}\``);
    }
  }
  lines.push("");

  lines.push(FOOTER);
  lines.push("");

  return lines.join("\n");
}

function summarize(newOnes: Violation[], fixed: Violation[]): string {
  const newItems =
    newOnes.length === 0
      ? ["- No new violations."]
      : newOnes.map((v) => `- \`${violationKey(v)}\`${v.impact ? ` (${v.impact})` : ""}`);
  const resolved =
    fixed.length === 0
      ? "No baseline violations resolved."
      : `${fixed.length} baseline ${fixed.length === 1 ? "violation" : "violations"} resolved.`;
  return [
    "## Accessibility report",
    "",
    "New accessibility violations not present in the baseline:",
    ...newItems,
    "",
    resolved,
    "",
    FOOTER,
  ].join("\n");
}

const FOOTER =
  "_Generated by loopy a11y-baseline. Fix new violations; growing the baseline (accepting debt) should be a deliberate, reviewed change._";

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 10);
}

export type { A11yScanner, Violation } from "./hooks/a11y.js";
export { fixedViolations, newViolations, violationKey } from "./hooks/a11y.js";
